### ISSUE TITLE
How to getByName on art layer?

### ISSUE THREAD

**Issue by MrTeferi** [loonghao/photoshop-python-api#101]
Is there a way to getByName on an art layer?
I know for layer sets its:
`app.activeDocument.layerSets.getByName(name_here)`

But I'm getting name error on:
`app.activeDocument.artLayers.getByName(name_here)`

Even though I see in the api that artLayers does have a method "getByName"...

**Comment by MrTeferi** [comment]
Also I noticed that layerSets "getByName" just iterates through all sets till it finds the right one, iterating through all layers/sets, or layers within sets etc noticeably slows my app down when compared with the native getByName method for javascript automation. Is this simply an inherent drawback of automating photoshop with python? Is there a better way we could be doing this that doesn't extend execution time so much?

**Comment by loonghao** [comment]
@MrTeferi This is the case.
because calling the interface through comtypes will have some functions that cannot be found, we can only deal with these in other ways.

**Comment by loonghao** [comment]
@MrTeferi I will update it later fix this issue of `artLayers.getByName`

**Comment by MrTeferi** [comment]
Thank you for the quick response!

**Comment by MrTeferi** [comment]
Looks like this issue is fixed, case closed :)
