### ISSUE TITLE
activeDocument.exportDocumen 使用不了

### ISSUE THREAD

**Issue by zjf8888** [loonghao/photoshop-python-api#138]
from photoshop import Session
import photoshop
import photoshop.api as psmain
if __name__ == '__main__':
    psdFile = 'Y:\\a.psd'
    with Session(psdFile, action="open", auto_close=True) as ps:
        ps.app.displayDialogs = ps.DialogModes.DisplayNoDialogs
        d = ps.ActionDescriptor();
        r = ps.ActionReference();
        r.putClass(ps.app.stringIDToTypeID("slice"));
        d.putReference(ps.app.stringIDToTypeID("null"), r);
        d.putClass(ps.app.stringIDToTypeID("using"), ps.app.stringIDToTypeID("guide"));
        # ps.app.executeAction(ps.app.stringIDToTypeID("make"), d, ps.DialogModes.NO);
        ps.app.executeAction(ps.app.stringIDToTypeID("make"), d);

        opts = ps.ExportOptionsSaveForWeb();
        opts.format = ps.SaveDocumentType.PNGSave
        opts.PNG8 = False;
        opts.quality = 100;

        pngFile = "f:/results/"

        ps.app.activeDocument.exportDocument(pngFile, ps.ExportType.SaveForWeb)

会报错

  File "D:\ProgramData\Anaconda3\lib\site-packages\comtypes\client\lazybind.py", line 161, in __getattr__
    descr = self.__bind(name, DISPATCH_METHOD | DISPATCH_PROPERTYGET)
  File "D:\ProgramData\Anaconda3\lib\site-packages\comtypes\client\lazybind.py", line 126, in __bind
    descr = self._tcomp.Bind(name, invkind)[1]
  File "D:\ProgramData\Anaconda3\lib\site-packages\comtypes\typeinfo.py", line 366, in Bind
    raise NameError("Name %s not found" % name)
NameError: Name exportDocument not found

**Comment by loonghao** [comment]
@zjf8888 
由于comtypes的绑定到photoshop的时候有些函数会出现类似问题，
我通过结合javascript的方式用来保证这个函数可以正常使用，
你可以更新最新的代码试试看还有没有其他问题

**Comment by loonghao** [comment]
@zjf8888 
相关参考
https://loonghao.github.io/photoshop-python-api/examples/#export-document
