### ISSUE TITLE
The exported PNG image is too large

### ISSUE THREAD

**Issue by javazhaoxiao** [loonghao/photoshop-python-api#147]
The same PSD file exported to PNG by PS is only 20+ KB, but exported to PNG by program is 20+ MB. For help

**Comment by loonghao** [comment]
@javazhaoxiao 

Can you provide the export options in your code?
Usually, it has something to do with your default options.

**Comment by javazhaoxiao** [comment]
My export options in my code is same to examples:https://loonghao.github.io/photoshop-python-api/examples/#export-layers-as-png         The following two pictures are my debug screenshots：dz3rpd7lgz61q.cloudfront.net/image/ae8cb7d638fdb6476a550880b27a215.png
dz3rpd7lgz61q.cloudfront.net/image/bcb3ddd8e2bfa209a86396a52e23e86.png

**Comment by loonghao** [comment]
@javazhaoxiao I have deployed a new version to fix that, please have an again.

**Comment by javazhaoxiao** [comment]
OK.Thanks
