### ISSUE TITLE
EPSSaveOptions

### ISSUE THREAD

**Issue by be42day** [loonghao/photoshop-python-api#153]
Hi,
When I run your sample code (in the README), I face this error:

 import photoshop.api as ps
  File "C:\Users\be42day\AppData\Local\Programs\Python\Python310\lib\site-packages\photoshop\_init_.py", line 2, in <module>
    from photoshop.session import Session
  File "C:\Users\be42day\AppData\Local\Programs\Python\Python310\lib\site-packages\photoshop\session.py", line 39, in <module>
    from photoshop.api import EPSSaveOptions
ImportError: cannot import name 'EPSSaveOptions' from 'photoshop.api' (C:\Users\be42day\AppData\Local\Programs\Python\Python310\lib\site-packages\photoshop\api\_init_.py)

And when I comment out this line (line 39 in session.py), your code runs properly.
Please check it

**Comment by loonghao** [comment]
Hi，@be42day Thank you for your found, I have deployed a new version to fix that, please use the latest version and try again, Cheers.

**Comment by loonghao** [comment]
@allcontributors please add @be42day for bug

**Comment by be42day** [comment]
Yes, it's ok.
@loonghao thanks for adding me as a contributor.
As a suggestion, I think it's better to change your sample code in the README. Now, the color of the text is white, so when a user wants to test the code, sees a blank image. But if you change its color, the user sees a colored text on the image.
For example, in green color :
```
text_color = ps.SolidColor()
text_color.rgb.red = 0
text_color.rgb.green = 255
text_color.rgb.blue = 0
```

> Hi，@be42day Thank you for your found, I have deployed a new version to fix that, please use the latest version and try again, Cheers.

**Comment by be42day** [comment]
Yes, it's ok.
@loonghao thanks for adding me as a contributor.
As a suggestion, I think it's better to change your sample code in the README. Now, the color of the text is white, so when a user wants to test the code, sees a blank image. But if you change its color, the user sees a colored text on the image.
For example, for green color :
```
text_color = ps.SolidColor()
text_color.rgb.red = 0
text_color.rgb.green = 255
text_color.rgb.blue = 0
```
