### ISSUE TITLE
app.documents.getByName Appears Broken?

### ISSUE THREAD

**Issue by MrTeferi** [loonghao/photoshop-python-api#162]
**Describe the bug**
app.documents.getByName does not appear to work, raises an error that "name getByName not found"

**To Reproduce**
```python
app = ps.Application()
document = app.documents.getByName("my-document-name.psd")
print(document)
# Will raise an error
```

**Expected behavior**
Find and retrieve the document object by its name

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Photoshop Version: Photoshop 2022
 - Python Version: python-3.8.x

**Screenshot**
![image](https://user-images.githubusercontent.com/92750180/178121549-08f9051f-2a58-4bdf-a036-d770ed992125.png)
![image](https://user-images.githubusercontent.com/92750180/178121554-ecb9895f-462e-4a01-814d-143f6b278328.png)

**Comment by loonghao** [comment]
@MrTeferi I will fix this soon.
There are many functions that may be inconsistent with the Photoshop javascript API after binding through COM, we need to patch them manually, I will create a new MR to fix this, thank you for your report.

**Comment by loonghao** [comment]
@MrTeferi 
I have deployed a new version, please try again, 
cheers.

**Comment by MrTeferi** [comment]
@loonghao Thanks Hal can confirm this definitely works for me now! Cheers buddy

**Comment by horiebin** [comment]
the problem appears again
layer = doc.artLayers.getByName("background")

KeyError: ('exportDocument', 3)

windows10 
photoshop 2020
python 3.6

**Comment by Investigamer** [comment]
> the problem appears again layer = doc.artLayers.getByName("background")
> 
> KeyError: ('exportDocument', 3)
> 
> windows10 photoshop 2020 python 3.6

I'll look into this using latest version when I get the chance. In the meantime, please post full code snippet. BTW, if I'm not mistaken you can now also get layers using dict key notation like this:
```py
layer = doc.artLayers['Layer Name']
```
Also keep in mind that accessing a layer via artLayers only works for layers, not layer groups. For layer groups you have to use layerSets like so:
```py
layer = doc.layerSets['Layer Group Name']
```
