### ISSUE TITLE
ActionDescriptor和ActionList的行为问题

### ISSUE THREAD

**Issue by TsXor** [loonghao/photoshop-python-api#169]
首先，我认为这件事不能用简单的“使用->出了bug”概括，因此我的描述如下。

首先执行这段代码
```python
import photoshop.api as ps
app = ps.Application()
nesteddesc1 = ps.ActionDescriptor()
nesteddesc2 = ps.ActionDescriptor()
nesteddesc1.putObject(specifictypeid,specifictypeid,nesteddesc2)
gotnesteddesc2 = nesteddesc1.getObject(specifictypeid)
```
好的，这一套操作下来，理论上`nesteddesc2`和`gotnesteddesc2`应当相同。
事实确实如此，使用它们的`isEqual`方法互相判断都会返回`True`，而对他俩任何一个的修改都会同步到另一个上。

那么同理，我们将嵌套的对象改成一个ActionList，上述操作即为：
```python
import photoshop.api as ps
app = ps.Application()
nesteddesc1 = ps.ActionDescriptor()
nestedlist2 = ps.ActionList()
nesteddesc1.putList(specifictypeid,nestedlist2)
gotnestedlist2 = nesteddesc1.getList(specifictypeid)
```
按照正常思维，`nestedlist2`和`gotnestedlist2`应当有差不多的性质，即“同一对象，修改同步”。
然而事实给了我一个大嘴巴子：`nestedlist2`和`gotnestedlist2`直接分道扬镳，对任何一方的修改都不会同步到另一方。
而且更令人内啥的是，对`gotnestedlist2`的修改也不会传递给`nesteddesc1`中嵌套的`ActionList`。也就是说你再执行：
```python
gotnestedlist2_another = nesteddesc1.getObject(specifictypeid)
```
`gotnestedlist2_another`也和`nestedlist2`和`gotnestedlist2`完全独立！

这时我便怀疑了一下本仓库：这种独立可能是因为本仓库的代码没有使python代码和ps的js api结合的足够紧密。
然后另一个细节让我怀疑了Adobe：`ActionList`是没有`isEqual`方法的。这也就意味着很可能判断两个`ActionList`是否相等是“无意义的”，因为`ActionDescriptor`的底层实现可能真的类似字典，但是`ActionList`的底层实现也可能真的和有序列表一点都不像（`ActionList`只能在末尾追加新元素，而且只能存放同类型元素也说明了这一点）。

我水平不够，这两种怀疑我也无法做出选择，Adobe那边我是不太敢问，因此我来问作者您了。

**Comment by TsXor** [comment]
简单地说，就是ActionDescriptor的放入和取出，就像存取的是一个指针，而ActionList的放入和取出，就像存取的是一个copy

**Comment by loonghao** [comment]
> 这种独立可能是因为本仓库的代码没有使python代码和ps的js api结合的足够紧密。

当前API 主要是利用COM接口去访问Photoshop暴露出来的接口，然后某些接口与Photoshop JS接口不可用的情况下，我们可以手动的做一些填补
类似这个，
https://github.com/loonghao/photoshop-python-api/blob/main/photoshop/api/_documents.py#L79

这里有自动生成的完整参考，你会发现根本没有这个`getByName` 这个函数

https://github.com/lohriialo/photoshop-scripting-python/blob/master/api_reference/photoshop_2020.py#L1838

所以有很多接口行为确实不如预期

**Comment by TsXor** [comment]
我尝试重写了ActionManager的3个类，做了一些优化，但是结果仍是ActionList存取与原件完全独立
