### ISSUE TITLE
"examples._psd_files" not found

### ISSUE THREAD

**Issue by Penguin-Valkyrie** [loonghao/photoshop-python-api#171]
Unable to "import examples._psd_files as psd"
I receive the exception: "No module named 'examples._psd_files"
The "examples" module is installed on my machine

Code(from "Exporting Layers as PNG"):
import os
from tempfile import mkdtemp

import examples._psd_files as psd

from photoshop import Session

PSD_FILE = psd.get_psd_files()

if __name__ == "__main__":
    psd_file = PSD_FILE["export_layers_as_png.png"]
    with Session(psd_file, action="open", auto_close=True) as ps:
        opts = ps.ExportOptionsSaveForWeb()

        png_file = os.path.join(mkdtemp(), "test.png")
        active_document = ps.app.activeDocument
        active_document.exportDocument(png_file, ps.ExportType.SaveForWeb, opts)
        os.startfile(png_file)

*My apologies for the initial misnaming and blank issue at first: this is my first time submitting an issue on Github. I also feel as though there is a simple step I missed somewhere along the way.

**Comment by loonghao** [comment]
Hi @Penguin-Valkyrie 
Example files are not included if you installed via pip.

PSD files in here:
https://github.com/loonghao/photoshop-python-api/tree/main/examples/files

You can replace this path with the absolute path of the PSD
```
psd_file = PSD_FILE["export_layers_as_png.png"]
```
