### ISSUE TITLE
ModuleNotFoundError: No module named 'winreg'

### ISSUE THREAD

**Issue by sshallow** [loonghao/photoshop-python-api#173]
**Describe the bug**
无法运行helloWord

**Desktop (please complete the following information):**
 - OS: MacOS
 - Python Version: [e.g. python-3.9]

https://user-images.githubusercontent.com/21257340/182178679-45aa9501-f118-4a10-9cbc-4258ff2e8eba.mov

#2

**Comment by loonghao** [comment]
@sshallow winreg是python在Windows系统中特有的默认库，当前API不支持MacOS系统

**Comment by TsXor** [comment]
虽然本仓库不支持，但还是有可能的：https://github.com/lohriialo/photoshop-scripting-python/tree/master/mac_scripting

**Comment by sshallow** [comment]
> 

这是脚本调用，和 api 没有关系了吧，（多谢，我去看看
