### ISSUE TITLE
Image's size changes after replacement.

### ISSUE THREAD

**Issue by Mossad-55** [loonghao/photoshop-python-api#174]
So this is my code for replacing an image :

from photoshop import Session

image = r"test2.png"
with Session() as ps:
    for layer in ps.active_document.layers:
        if layer.name == "PIC":
            ps.active_document.activeLayer = layer
            replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
            desc = ps.ActionDescriptor
            idnull = ps.app.charIDToTypeID("null")
            desc.putPath(idnull, image)
            ps.app.executeAction(replace_contents, desc)
            break

It works and replaces the image in the specific layer but the size of it gets way bigger, so is there a way to fix that issue ?!

**Comment by loonghao** [comment]
@Mossad-55 
You need to make sure your two images are the same size, otherwise, you need to replace and rescale

**Comment by Mossad-55** [comment]
Both are same sizes but how could i rescale them rescale them or put proper properties in the resize() method because when i put values in it with the same height and width it doesn't work too and the size isn't equal to the one i passed it in.

**Comment by loonghao** [comment]
Hi, @Mossad-55 I have updated the example for replacing the image, please take a look.
https://github.com/loonghao/photoshop-python-api/pull/175/files
