### ISSUE TITLE
Don't understand how to select certain font

### ISSUE THREAD

**Issue by blunderedbishop** [loonghao/photoshop-python-api#176]
I'm creating a simple paragraph text with 
```
new_text_layer = doc.artLayers.add()
new_text_layer.kind = ps.LayerKind.TextLayer
new_text_layer.textItem.kind = ps.TextType.ParagraphText
print(new_text_layer.textItem.font)
```
I have managed to list all available fonts with
```
app = ps.Application()
app.fonts.getByName('CC Wild Words Roman')
```
By modifying `api/_text_fonts` I was able to print out all fonts available, and I can conferm that 'CC Wild Words Roman' is there. But I can't set it! I saw in the `manual test` files that you set it like `textItem.font='AdobeThai-Regular'`, where the name is `'Adobe Thai'`
But none of the following work:
```
new_text_layer.textItem.font='CC Wild Words Roman'
new_text_layer.textItem.font='CC-Wild-Words-Roman'
new_text_layer.textItem.font='CCWildWords-Roman'
```
What am I supposed to do?

**Comment by blunderedbishop** [comment]
Ok, thanks to [this](https://stackoverflow.com/questions/28948059/photoshop-script-to-change-font-and-font-size) I was able to figure out that you're supposed to provide the postscript name, which you can get by 
```textItem.postScriptName # 'CCWildWordsRoman'
new_text_layer.textItem.font='CCWildWordsRoman' #works
````
The issue can be closed.

**Comment by MrTeferi** [comment]
You can set the font using its regular name like so:
```python
import photoshop.api as ps
app = ps.Application()

layer = app.activeDocument.layers.getByName("My Text Layer")
layer.textItem.font = app.fonts.getByName("Font Name").postScriptName
```
