### ISSUE TITLE
Cannot replace an image layer

### ISSUE THREAD

**Issue by Edimo05** [loonghao/photoshop-python-api#177]
**Describe the bug**
I am trying to replace an image layer in a photoshop file. For that purpose I am using this next code:

**To Reproduce**
This is my python code:
with Session() as ps:
    replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
    desc = ps.ActionDescriptor
    idnull = ps.app.charIDToTypeID("null")
    desc.putPath(idnull, "G:\\BLEBLE\\BLABLABLA\\BLABLABLA\\BLABLABL\\BLABLA\\2022\\August\\Images\\09.jpeg")
    ps.app.executeAction(replace_contents, desc)

**Expected behavior**
It suppose to replace already existing image layer but instead of thar it show an error message and log.

**Screenshots**
Photoshop error message:
![image](https://user-images.githubusercontent.com/94873872/184283241-c3b7a0b7-ef67-46a3-9877-6b5102a92d30.png)

Terminal message:
Traceback (most recent call last):
  File "g:\Blebleble\blablabla\blablabla\blablabla\Publicaciones\AUTOMATION\automate.py", line 43, in <module>
    ps.app.executeAction(replace_contents, desc)
  File "C:\Users\bliblibli\AppData\Local\Programs\Python\Python310\lib\site-packages\photoshop\api\application.py", line 355, in executeAction
    return self.app.executeAction(event_id, descriptor, display_dialogs)
  File "C:\Users\bliblibli\AppData\Local\Programs\Python\Python310\lib\site-packages\comtypes\client\lazybind.py", line 182, in caller
    return self._comobj._invoke(descr.memid, descr.invkind, 0, *args)
  File "C:\Users\bliblibli\AppData\Local\Programs\Python\Python310\lib\site-packages\comtypes\automation.py", line 745, in _invoke
    self.__com_Invoke(memid, riid_null, lcid, invkind,
_ctypes.COMError: (-2147213497, None, (None, None, None, 0, None))

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Photoshop Version: Adobe Photoshop Version: 22.5.4 20211208.r.631 a0cb269  x64
 - Python Version: python-3.10

**Additional context**
This code actually worked once but suddenly it stopped working.

**Comment by blunderedbishop** [comment]
Sorry but I can't help you directly. Though this happened to me too (including the code working only once), and I worked around it by simply [importing](https://loonghao.github.io/photoshop-python-api/examples/#import-image-as-layer) the new image and getting rid of the old one in another way.

**Comment by blunderedbishop** [comment]
Have you tried look at #174? What's missing in your code is setting the active layer: `ps.active_document.activeLayer = layer`.

**Comment by loonghao** [comment]
@Edimo05 
You can try to add `r` in the file path, to ensure the code use raw path
```
desc.putPath(idnull, r"G:\BLEBLE\BLABLABLA\BLABLABLA\BLABLABL\BLABLA\2022\August\Images\09.jpeg")
```

**Comment by Edimo05** [comment]
> 

I tried, still same error message

**Comment by Edimo05** [comment]
> > 
> 
> I tried, still same error message



> @Edimo05 You can try to add `r` in the file path, to ensure the code use raw path
> 
> ```
> desc.putPath(idnull, r"G:\BLEBLE\BLABLABLA\BLABLABLA\BLABLABL\BLABLA\2022\August\Images\09.jpeg")
> ```

I tried and doesn't work. Still getting the same error.

**Comment by Edimo05** [comment]
@loonghao I tried this code (https://loonghao.github.io/photoshop-python-api/examples/#replace-images) but when I cannot import examples._psd_files. I already installed photoshop_python_api.

**Comment by Edimo05** [comment]
> Have you tried to look at #174? What's missing in your code is setting the active layer: `ps.active_document.activeLayer = layer`. Maybe that'll work.

I tried change my code to this:
with Session() as ps:
    ps.active_document.activeLayer = doc.ArtLayers["08"]
    replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
    desc = ps.ActionDescriptor
    idnull = ps.app.charIDToTypeID("null")
    desc.putPath(idnull, r"G:\BLEBLE\BLABLABLA\BLABLABLA\BLABLABL\BLABLA\2022\August\Images\09.jpeg")
    ps.app.executeAction(replace_contents, desc)

and it shows next error:
Traceback (most recent call last):
  File "g:\Blebleble\blablabla\blablabla\blablabla\Publicaciones\AUTOMATION\automate.py", line 40, in <module>
    ps.active_document.activeLayer = doc.ArtLayers["08"]
  File "C:\Users\bliblibli\AppData\Local\Programs\Python\Python310\lib\site-packages\photoshop\api\_document.py", line 83, in activeLayer
    self.app.activeLayer = layer
  File "C:\Users\bliblibli\AppData\Local\Programs\Python\Python310\lib\site-packages\comtypes\client\lazybind.py", line 218, in __setattr__
    self._comobj._invoke(descr.memid, descr.invkind, 0, value)
  File "C:\Users\bliblibli\AppData\Local\Programs\Python\Python310\lib\site-packages\comtypes\automation.py", line 737, in _invoke
    array[i].value = a
  File "C:\Users\bliblibli\AppData\Local\Programs\Python\Python310\lib\site-packages\comtypes\automation.py", line 231, in _set_value
    elif (hasattr(value, '__len__') and len(value) == 0
  File "C:\Users\bliblibli\AppData\Local\Programs\Python\Python310\lib\site-packages\win32com\client\dynamic.py", line 303, in __len__
    raise TypeError("This dispatch object does not define a Count method")
TypeError: This dispatch object does not define a Count method

maybe I placed that code u mentioned wrong?

**Comment by loonghao** [comment]
@Edimo05 
ArtLayers is a list, you need artLayer + index to access it
```
doc.ArtLayers["08"]
```
```python
with Session() as ps:
    ps.active_document.activeLayer = doc.artLayers.getByName("08")
    replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
    desc = ps.ActionDescriptor
    idnull = ps.app.charIDToTypeID("null")
    desc.putPath(idnull, r"G:\BLEBLE\BLABLABLA\BLABLABLA\BLABLABL\BLABLA\2022\August\Images\09.jpeg")
    ps.app.executeAction(replace_contents, desc)
````

**Comment by Edimo05** [comment]
> @Edimo05 ArtLayers is a list, you need artLayer + index to access it
> 
> ```
> doc.ArtLayers["08"]
> ```
> 
> ```python
> with Session() as ps:
>     ps.active_document.activeLayer = doc.artLayers.getByName("08")
>     replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
>     desc = ps.ActionDescriptor
>     idnull = ps.app.charIDToTypeID("null")
>     desc.putPath(idnull, r"G:\BLEBLE\BLABLABLA\BLABLABLA\BLABLABL\BLABLA\2022\August\Images\09.jpeg")
>     ps.app.executeAction(replace_contents, desc)
> ```

@loonghao now is showing this error:
Traceback (most recent call last):
  File "g:\Blebleble\blablabla\blablabla\blablabla\Publicaciones\AUTOMATION\automate.py", line 55, in <module>
    ps.active_document.activeLayer = doc.ArtLayers.getByName("08")
  File "C:\Users\bliblibli\AppData\Local\Programs\Python\Python310\lib\site-packages\win32com\client\dynamic.py", line 628, in __getattr__
    ret = self._oleobj_.Invoke(retEntry.dispid, 0, invoke_type, 1)
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Adobe Photoshop', 'Illegal argument - argument 1\n- Required value is missing', None, 0, -2147220262), None)

**Comment by loonghao** [comment]
@Edimo05 

```
doc.ArtLayers.getByName("08") 
```
`ArtLayers` first letter lowercase
```
doc.artLayers.getByName("08")
```

**Comment by Edimo05** [comment]
> @Edimo05
> 
> ```
> doc.ArtLayers.getByName("08") 
> ```
> 
> `ArtLayers` first letter lowercase
> 
> ```
> doc.artLayers.getByName("08")
> ```

@loonghao nothing man, same error:

Traceback (most recent call last):
  File "g:\Blebleble\blablabla\blablabla\blablabla\Publicaciones\AUTOMATION\automate.py", line 75, in <module>
    ps.active_document.activeLayer = doc.artLayers.getByName("08")
  File "C:\Users\bliblibli\AppData\Local\Programs\Python\Python310\lib\site-packages\win32com\client\dynamic.py", line 628, in __getattr__
    ret = self._oleobj_.Invoke(retEntry.dispid, 0, invoke_type, 1)
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Adobe Photoshop', 'Illegal argument - argument 1\n- Required value is missing', None, 0, -2147220262), None)

**Comment by loonghao** [comment]
@Edimo05 
replace image only support ArtLayer as a smart object layer
![image](https://user-images.githubusercontent.com/13111745/184501513-612d8dcb-3c98-4542-89bb-a073dbd0175e.png)

Please convert the 08 layer as a smart-object first and then execute the following code
```python
from photoshop import Session

with Session() as ps:
    doc = ps.active_document
    doc.activeLayer = doc.artLayers.getByName("08")
    replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
    desc = ps.ActionDescriptor
    idnull = ps.app.charIDToTypeID("null")
    desc.putPath(idnull, r"G:\BLEBLE\BLABLABLA\BLABLABLA\BLABLABL\BLABLA\2022\August\Images\09.jpeg")
    ps.app.executeAction(replace_contents, desc)
```

**Comment by Edimo05** [comment]
> @Edimo05 replace image only support ArtLayer as a smart object layer ![image](https://user-images.githubusercontent.com/13111745/184501513-612d8dcb-3c98-4542-89bb-a073dbd0175e.png)
> 
> Please convert the 08 layer as a smart-object first and then execute the following code
> 
> ```python
> from photoshop import Session
> 
> with Session() as ps:
>     doc = ps.active_document
>     doc.activeLayer = doc.artLayers.getByName("08")
>     replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
>     desc = ps.ActionDescriptor
>     idnull = ps.app.charIDToTypeID("null")
>     desc.putPath(idnull, r"G:\BLEBLE\BLABLABLA\BLABLABLA\BLABLABL\BLABLA\2022\August\Images\09.jpeg")
>     ps.app.executeAction(replace_contents, desc)
> ```

@loonghao finally works. That layer was already an smart object, I think I missed ps.active_document.
Thanks a lot!!!

**Comment by loonghao** [comment]
@Edimo05 good to hear, closing issue.
