### ISSUE TITLE
Some SaveOptions tuning missing.

### ISSUE THREAD

**Issue by voodraizer** [loonghao/photoshop-python-api#21]
Hi,
I'm trying to save tga but it's not implemented. Like this TargaSaveOptions().

Also can't find how to set bits for save image (in 'js-code' saveOptions.resolution = TargaBitsPerPixels.THIRTYTWO)

**Comment by loonghao** [comment]
Hi @voodraizer,
Thank you for your report.
I have been Implemented and fix these issues.
you can try the latest version.
Let me know if updates are work for you.

two examples:
- https://photoshop-python-api.readthedocs.io/en/master/examples.html#operation-layer-set
- https://photoshop-python-api.readthedocs.io/en/master/examples.html#operation-channels

**Comment by voodraizer** [comment]
Hi @loonghao.
Its work like a charm. Thank you.
