### ISSUE TITLE
Compatibility with PyCharm

### ISSUE THREAD

**Issue by Wang-Walexr** [loonghao/photoshop-python-api#217]
I'm having difficulty using the api with Pycharm. Would I need to install addition plugin(s) to be able to do that?

**Comment by loonghao** [comment]
Are there any specific error screenshots or logs?

**Comment by Wang-Walexr** [comment]
![pycharm](https://user-images.githubusercontent.com/70092481/209296766-d1fe105c-dacf-4996-b7c8-6bf466c952f1.png)

This is what I get when I use with pycharm

![vsc](https://user-images.githubusercontent.com/70092481/209296905-d6e511ae-0641-4b0e-8427-2e021889e44d.png)

And everything looks fine with Visual Studio Code

**Comment by loonghao** [comment]
@Wang-Walexr 
First you need to make sure that the python interpreter in your pycharm is the same as VScode
![image](https://user-images.githubusercontent.com/13111745/209468649-fd64b4a2-7b68-4691-bc8b-d5c97bc44458.png)

**Comment by Wang-Walexr** [comment]
Changing the interpreter to what VSC use solved it. Was using the wrong interpreter

Thank you @loonghao
