### ISSUE TITLE
Works only on Windows?

### ISSUE THREAD

**Issue by LevanGelashvili** [loonghao/photoshop-python-api#232]
**Describe the bug**
Does it only work on windows? Needs a 'winreg' module apparently.

**To Reproduce**
Run a python file with imports on a Mac device.

**Screenshots**
![image](https://user-images.githubusercontent.com/42913712/220634373-a292615f-0b86-4b3c-8477-ee20dd319165.png)

**Desktop (please complete the following information):**
 - OS: [MacOS Ventura 13.0.1]
 - Python Version: [python-3.9]

**Comment by loonghao** [comment]
Hi @LevanGelashvili This API only work on Windows.

**Comment by LevanGelashvili** [comment]
:( ok thanks

**Comment by Tilix4** [comment]
I think you must advertise this fact in the top of the `README.md`, it'd have saved me few hours trying to find out what was going on :)
