### ISSUE TITLE
Flask库是否没办法使用这个工具呢？

### ISSUE THREAD

**Issue by sgajs** [loonghao/photoshop-python-api#254]
我试着用Flask构建网页窗口，并通过按钮经photoshop-python-api操控Photoshop。但用按钮操控时报错：photoshop.api.errors.PhotoshopPythonAPIError: Please check if you have Photoshop installed correctly.

不用flask构建的网页按钮则可以正常使用photoshop-python-api操控Photoshop。
以下是我的代码：
python：
from flask import Flask
from photoshop import Session
app = Flask(__name__)
@app.route('/tryButton', methods=['GET','POST'])
def tryButton():
    with Session(r"C:\Users\out.psd", action="open") as app:
        doc = app.active_document
if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0",port=5000)
    return "File uploaded successfully"

Js：
tryButton.addEventListener('click', function() {
        fetch('/tryButton', {
            method: 'GET',
        }).then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.blob();
        }).then(blob => {

        }).catch(error => {
            console.error('Error:', error);
        });
    });

HTML：
<!DOCTYPE html>
<html>
<head>
</head>
<body>
        <input type="button" value="try"><br>
</body>
</html>

是否是flask的多线程造成的？请问有什么好的解决办法吗？

**Comment by loonghao** [comment]
应该是可以的你可以参考这个
https://github.com/loonghao/photoshop-python-api/issues/161

**Comment by sgajs** [comment]
解决了，似乎因为flask是多线程的，使用pypsAPI时需要创建COM对象，为避免线程冲突和资源争夺，需要在使用前初始化一下com环境。直接运行好像因为python会自动回收处理COM环境而不受影响？修改代码如下：
```
from flask import Flask
import photoshop.api as ps
import pythoncom

app = Flask(__name__)
path=r"F:\try\lxzj.psd"

# @app.route('/',methods=['GET'])
@app.route('/')
def index():
    try:
        pythoncom.CoInitialize() #初始化com环境
        a()
    finally:
        pythoncom.CoUninitialize() #清理com环境
    return ''

def a():
    psapp=ps.Application()
    psapp.Open(path)
    psApp = psapp.Application.ActiveDocument

if __name__ == '__main__':
    # a()
    app.run(debug=True)
```
这样就可以正常运行了
