### ISSUE TITLE
I want to get a group of layers how to operate it

### ISSUE THREAD

**Issue by irx999** [loonghao/photoshop-python-api#270]
I want to get a group of layers how to operate it
我想获取一个组里面的图层怎么操作呢， 好像一个图层不可见了也没有用ps.active_document.artLayers.getByName("123")获取

**Comment by loonghao** [comment]
@irx999 你可以参考这个例子，
https://loonghao.github.io/photoshop-python-api/examples/#move-to-end
这个例子是把一个图层创建后移动到组里面，组在PS里面叫layerSets
