### ISSUE TITLE
How to Open Smart Object;

### ISSUE THREAD

**Issue by kkgg0521** [loonghao/photoshop-python-api#273]

**Comment by kkgg0521** [comment]
How to open a smart object in my PSD？

**Comment by kkgg0521** [comment]
> `    def openSmartObject(self):
        a = ps.Application().stringIDToTypeID("placedLayerEditContents")
        d = ps.ActionDescriptor()
        ps.Application().executeAction(a, d)`
hello i Solved this problem on my own

**Comment by lzzkey** [comment]
Thank you very much. I have succeeded in using your plan. Thank you.

**Comment by wangxshuai** [comment]
> > `    def openSmartObject(self):         a = ps.Application().stringIDToTypeID("placedLayerEditContents")         d = ps.ActionDescriptor()         ps.Application().executeAction(a, d)`
> > hello i Solved this problem on my own

前辈你这个问题帮助了我很多，我还有一些问题想请教，我现在想在你的解决方法的基础上，替换新打开的智能对象中文字，我现在打开智能对象后就不知道该如何去操作了，情不能指教一下，非常感谢！

import photoshop.api as ps
App = ps.Application()
doc = App.load('*.psd')

a = App.stringIDToTypeID("placeLayerEditContents")
b = ps.ActionDscriptor()
App.executeAction(a,b)

now I open the smart object,  but i have no idea to change the text in the opened smart object, how to seleted the opened smart object layer,? And how to change the text in the opened smart object layer  ?

**Comment by PcAlien** [comment]
Mhh.. that is not working for me. Photoshop complains (translated):
The command "<unknown>" is not available"
Any ideas?
