### ISSUE TITLE
多次替换psd中同一个图片，并在每次替换后将替换后的psd保存为png。在这个过程的第二次开始，它会将上一次保存的png替换到想要替换的图层上，描述可能有点不清晰，代码如下

### ISSUE THREAD

**Issue by white-26** [loonghao/photoshop-python-api#276]
```
from photoshop import Session

def BatchChange(picPath, picName):
    with Session("D:/newT.psd", action="open") as ps:
        active_layer = ps.active_document.activeLayer
        bounds = active_layer.bounds
        replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
        desc = ps.ActionDescriptor
        idnull = ps.app.charIDToTypeID("null")
        desc.putPath(idnull, picPath)
        ps.app.executeAction(replace_contents, desc)

        # replaced image.
        active_layer = ps.active_document.activeLayer
        current_bounds = active_layer.bounds
        width = bounds[2] - bounds[0]
        height = bounds[3] - bounds[1]

        current_width = current_bounds[2] - current_bounds[0]
        current_height = current_bounds[3] - current_bounds[1]
        new_size = width / current_width * 100
        active_layer.resize(new_size, new_size, ps.AnchorPosition.MiddleCenter)
        active_document = ps.app.activeDocument
        active_document.saveAs(f"D:/psdResult/{picName}.png", ps.PNGSaveOptions(), asCopy=True)

for i in range(3):
    BatchChange(f"D:/pic_{i + 1}.png", f"pic_{i + 1}")
```

**Comment by Nomination-NRB** [comment]
> ```
> from photoshop import Session
> 
> def BatchChange(picPath, picName):
>     with Session("D:/newT.psd", action="open") as ps:
>         active_layer = ps.active_document.activeLayer
>         bounds = active_layer.bounds
>         replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
>         desc = ps.ActionDescriptor
>         idnull = ps.app.charIDToTypeID("null")
>         desc.putPath(idnull, picPath)
>         ps.app.executeAction(replace_contents, desc)
> 
>         # replaced image.
>         active_layer = ps.active_document.activeLayer
>         current_bounds = active_layer.bounds
>         width = bounds[2] - bounds[0]
>         height = bounds[3] - bounds[1]
> 
>         current_width = current_bounds[2] - current_bounds[0]
>         current_height = current_bounds[3] - current_bounds[1]
>         new_size = width / current_width * 100
>         active_layer.resize(new_size, new_size, ps.AnchorPosition.MiddleCenter)
>         active_document = ps.app.activeDocument
>         active_document.saveAs(f"D:/psdResult/{picName}.png", ps.PNGSaveOptions(), asCopy=True)
> 
> for i in range(3):
>     BatchChange(f"D:/pic_{i + 1}.png", f"pic_{i + 1}")
> ```

请问修改图片大小可以实现吗，替换图片后，从# replaced image.这一行开始就报错了
