### ISSUE TITLE
How to revert changes?

### ISSUE THREAD

**Issue by ulyverse** [loonghao/photoshop-python-api#296]
I would like to revert to an earlier saved state after making changes.

On javascript you can do something like this:
```
var savedState = app.activeDocument.activeHistoryState;
//do something
app.activeDocument.activeHistoryState = savedState;
```

but this doesn't work in python
```
savedState = app.activeDocument.activeHistoryState
#do something
app.activeDocument.activeHistoryState = savedState
```

it throws this error: 
`AttributeError: can't set attribute 'activeHistoryState'`

 activeHistoryState appears to be readonly, is there a different way to revert back using this api? thanks!

**Comment by loonghao** [comment]
I deployed a new version and the issue has been solved
