### ISSUE TITLE
Cannot download photoshop_python_integration

### ISSUE THREAD

**Issue by chwjshlwel** [loonghao/photoshop-python-api#32]
Hello, I want to download photoshop_python_integration. But when I click the download, I got a message that "Please contact the file owner and ask him to grant you access".
 How I can download it?

**Comment by loonghao** [comment]
@chwjshlwel 

Thank you for your interesting this project:

https://drive.google.com/drive/folders/1jPFud2KU9zulrTlldU7MyxfFN9iaRHQE?usp=sharing

Enjoy~

if you need any support please let me knows.
