### ISSUE TITLE
AttributeError: module 'photoshop.api' has no attribute 'LayerKind'

### ISSUE THREAD

**Issue by enzozhong** [loonghao/photoshop-python-api#33]
**Describe the bug**
when i run photoshop-python-api-master\examples\hello_world.py

full log

Traceback (most recent call last):
  File "hello_world.py", line 22, in <module>
    hello_world()
  File "hello_world.py", line 10, in hello_world
    new_text_layer.kind = ps.LayerKind.TextLayer
AttributeError: module 'photoshop.api' has no attribute 'LayerKind'

my py version 3.7.4

**Comment by loonghao** [comment]
@enzozhong Thank you for reporting the error. Check again frequently and find some omissions in the code in some examples. I will update it as soon as possible. Thank you again.

**Comment by loonghao** [comment]
@all-contributors please add @enzozhong for Bug reports.

**Comment by loonghao** [comment]
@enzozhong I have deployed a new version `0.12.1`, let me if that is work for you. Cheers.

**Comment by enzozhong** [comment]
@loonghao  , Thanks for your quick response.New version 0.12.1 run successfully.
