### ISSUE TITLE
希望可以添加 接受 ps 消息弹框的 接口，如 缺失字体等等

### ISSUE THREAD

**Issue by kkgg0521** [loonghao/photoshop-python-api#341]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows10, Windows7]
 - Photoshop Version: [e.g. Photoshop-2020]
 - Python Version: [e.g. python-3.6]

**Additional context**

**Comment by loonghao** [comment]
你能给更多的上下文信息么？这个API主要就是调用ps默认已有的能力。

**Comment by kkgg0521** [comment]
你好 ，假设我的电脑没有这个字体， 用这个Api 去操作psd的话  ，他会存在一个 告诉你需要添加 或者 替换的字体的 消息框，我没有办法使用这个api 去处理这个消息框
