### ISSUE TITLE
可以同时操作两个ps 吗？

### ISSUE THREAD

**Issue by kkgg0521** [loonghao/photoshop-python-api#346]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows10, Windows7]
 - Photoshop Version: [e.g. Photoshop-2020]
 - Python Version: [e.g. python-3.6]

**Additional context**

**Comment by loonghao** [comment]
不能，这是ps的限制，只能有一个实例存在
