### ISSUE TITLE
How to visit all the text layers?

### ISSUE THREAD

**Issue by zjj1997zju** [loonghao/photoshop-python-api#358]
I want to iterate through all text layers in a PSD file and retrieve the position and bounding box of each text layer. 
My PSD file has a complex layer structure, and after reading some examples, I'm unsure how to recursively access all layers.

Can anyone help?

**Comment by lord-dubious** [comment]
if u find out let  me know

**Comment by loonghao** [comment]
```
import photoshop.api as ps

app = ps.Application()
for layer in app.activeDocument.layers:
    print(layer.typename)
    print(layer.bounds)
```

**Comment by laughingg** [comment]
> 您可以尝试下面的代码。
> 
> import photoshop.api as ps
> 
> app = ps.Application()
> for layer in app.activeDocument.layers:
>     print(layer.typename)
>     print(layer.bounds)


    for layer in ps.active_document.layers:
        print("layers: layer.kind:", layer.typename, LayerKind(layer.kind))


log info;
layers: layer.kind: ArtLayer LayerKind.GradientFillLayer
layers: layer.kind: ArtLayer LayerKind.GradientFillLayer
layers: layer.kind: ArtLayer LayerKind.GradientFillLayer
layers: layer.kind: ArtLayer LayerKind.GradientFillLayer
layers: layer.kind: ArtLayer LayerKind.GradientFillLayer
layers: layer.kind: ArtLayer LayerKind.GradientFillLayer
layers: layer.kind: ArtLayer LayerKind.GradientFillLayer
layers: layer.kind: ArtLayer LayerKind.GradientFillLayer


psd file doc layer info screenshot :

![Image](https://github.com/user-attachments/assets/bbaab3b9-75e4-46d4-a325-c71951668066)

**Comment by laughingg** [comment]
I need to obtain the complete layer structure. But I failed in my operation.

@loonghao @Issues-translate-bot @feisuzhu

**Comment by laughingg** [comment]
![Image](https://github.com/user-attachments/assets/30bd90b6-79d4-4a6d-9641-96e7c6de9390)

LayerKind.CurvesLayer is group ?
