### ISSUE TITLE
how does jsx load python code (addfilter.py) directly not in cmd window

### ISSUE THREAD

**Issue by chwjshlwel** [loonghao/photoshop-python-api#36]
Dear author,
First, thanks for your great job.
The pythonIDE is good for developers, but in fact for users they just want click on button and get the result they want and they do not know what is python. 
If I do not want to show the cmd window and I want the jsx file runs or loads the python code (addfilter.py)  directly and show the result in photoshop, what I should do?
Or is there any references to learn how to do this?
I search on internet, but it has few information about how jsx connects with python or loads python.

**Comment by loonghao** [comment]
Hi @chwjshlwel ,
Thank you for your like, if you want to via JSX file to call python code you can reference this [code](https://github.com/loonghao/pyblish-photoshop/blob/master/pyblish_photoshop/cli.py#L52).

In below example can help us create a menu in photoshop.
```javascript
/*
// BEGIN__HARVEST_EXCEPTION_ZSTRING
<javascriptresource>
<name>pyblish</name>
<about>Pyblish for Photoshop.</about>
<category>photoshop</category>
<menu>filter</menu>
</javascriptresource>
// END__HARVEST_EXCEPTION_ZSTRING
   The item tagged "name" specifies the localized name or ZString that will be displayed in the menu
   The item tagged "menu" specifies the menu in which the command will appear: generate, automate, scripts, or filter
   The item tagged "enableinfo" specifies the conditions under which the command will be enabled. Too complex to describe here; see plugin sdk. Should usually just be "true", and your command should report a user-comprehensible error when it can't handle things. The problem with disabling the command when it's unsuitable is that there's no hint to the user as to why a command is disabled.
   The item tagged "about" specifies the localized text or ZString to be displayed in the about box for the plugin. Optional.
   The item tagged "eventid" needs to be a guaranteed unique string for your plugin. Usually generated with a UUID generator like uuidgen on MacOS
*/
{
app.system("start python your/python/file.py")
}    
```
another suggestion is we can use Qt create a Qt widget to deploy us scripts and use The above way to launch.

please let me know if that works for you.

**Comment by loonghao** [comment]
Hi @chwjshlwel I just want to confirm that is all works for you?
