### ISSUE TITLE
Export PNG image

### ISSUE THREAD

**Issue by JHD1159351858** [loonghao/photoshop-python-api#381]
How can I achieve functions like quick exporting to PNG when I have multiple art palettes in my Photoshop?For example, I manually exported 9 images instead of exporting them as 1 because there are nine drawing boards in one PSD file

**Comment by loonghao** [comment]
This is an example for export boards as images
https://loonghao.github.io/photoshop-python-api/examples/#export-artboards

**Comment by JHD1159351858** [comment]
Thank you so much. This is very useful to me




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月30日(星期一) 凌晨0:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [loonghao/photoshop-python-api] Export PNG image (Issue #381)














 
This is an example for export boards as images
 https://loonghao.github.io/photoshop-python-api/examples/#export-artboards
