### ISSUE TITLE
Document.activeLayer fails with Photoshop 2025

### ISSUE THREAD

**Issue by BobbyCephy** [loonghao/photoshop-python-api#382]
Executing

[`def activeLayer(self) -> PS_Layer:`
](https://github.com/loonghao/photoshop-python-api/blob/main/photoshop/api/_document.py#L88)

leads to error

> COMError: (-2147352567, 'Ausnahmefehler aufgetreten.', ('Illegal argument - argument 1\n- Required value is missing', 'Adobe Photoshop', None, 0, -2147220262))

caused by

[`type_ = self.eval_javascript("app.activeDocument.activeLayer.typename")`
](https://github.com/loonghao/photoshop-python-api/blob/main/photoshop/api/_document.py#L90)

**Desktop**
 - OS: Windows10
 - Photoshop Version: Photoshop-2025
 - Python Version: python-3.11

**Comment by loonghao** [comment]
Test environment Photoshop 2025
```python
from photoshop.api import Application
app = Application()
type_ = app.eval_javascript("app.activeDocument.activeLayer.typename")
print(type_)
```
![image](https://github.com/user-attachments/assets/8a60f6b9-2556-46fc-b2bc-12e7a6fd60e1)

**Comment by BobbyCephy** [comment]
Thanks for the convincing test! Now that I was sure that the error was on my side, I found it: a stupid test script photoshop.py was in my path. Thank you so much for your excellent API!
