### ISSUE TITLE
How to crop a Image?

### ISSUE THREAD

**Issue by blankeistein** [loonghao/photoshop-python-api#40]
How do I crop an image? I have trouble finding arguments for cropping an image. Thank you

**Comment by loonghao** [comment]
Hi @blankeistein 

I usually go to the link below to find the corresponding document.
- https://theiviaxx.github.io/photoshop-docs/Photoshop/Document/crop.html?highlight=crop
- https://www.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-javascript-ref-2020.pdf

And I add a new example for cropping.
https://photoshop-python-api.readthedocs.io/en/0.14.0/examples.html#cropping

Let me know if that can help you.

**Comment by blankeistein** [comment]
Yes this helps me. thank you 👍🏼

**Comment by loonghao** [comment]
Awesome~ Closing the issues, Cheers.
