### ISSUE TITLE
How to modify color fill layer

### ISSUE THREAD

**Issue by kratosvn** [loonghao/photoshop-python-api#42]
Hi guys,

I want to change color of fill layer. I just tried change color by selection.fill but app return error: The command Fill is not current available.

here my code:
`colorObj = Dispatch("Photoshop.SolidColor")
                        colorObj.RGB.Red = rgb_strip[0]
                        colorObj.RGB.Green = rgb_strip[1]
                        colorObj.RGB.Blue = rgb_strip[2]

                        art_file.Selection.Fill(colorObj)`

**Comment by loonghao** [comment]
Hi @kratosvn,

You can try use this api.

below is a example:
https://photoshop-python-api.readthedocs.io/en/master/examples.html.#fill-selection

Cheers,

**Comment by kratosvn** [comment]
Hi @loonghao,

I just tried your example but the error cant resolve.
Can you help me try with this file:
[Uploading n
[name.psd.zip](https://github.com/loonghao/photoshop-python-api/files/5660897/name.psd.zip)
ame.psd…]()

thank you so munch

**Comment by loonghao** [comment]
Hi @kratosvn  I checked your PSD file for you. I guess the reason you can’t execute successfully is because you can’t execute selection and fill if it is not artLayer in PSD
![demo (3)](https://user-images.githubusercontent.com/13111745/101700966-f395b400-3ab8-11eb-9b7c-6a560f0f7051.gif)

**Comment by loonghao** [comment]
@kratosvn In the gif below I reproduced the issue you encountered, and then successfully performed color filling according to the selection through the API.  Let me know if that can work for you, Cheers.

![demo (4)](https://user-images.githubusercontent.com/13111745/101701645-4623a000-3aba-11eb-8951-a8e8d9656ea0.gif)

and the code:
```python
# Fill the current selection with an RGB color.

from photoshop import Session

with Session() as ps:
    start_ruler_units = ps.app.Preferences.RulerUnits

    if len(ps.app.documents) < 1:
        if start_ruler_units is not ps.Units.Pixels:
            ps.app.Preferences.RulerUnits = ps.Units.Pixels
        docRef = ps.app.documents.add(
            320, 240, 72, None, ps.NewDocumentMode.NewRGB,
            ps.DocumentFill.White
        )
        docRef.artLayers.add()
        ps.app.preferences.rulerUnits = start_ruler_units

    if not ps.active_document.activeLayer.isBackgroundLayer:
        selRef = ps.active_document.selection
        fillcolor = ps.SolidColor()
        fillcolor.rgb.red = 0
        fillcolor.rgb.green = 0
        fillcolor.rgb.blue = 0
        selRef.fill(fillcolor, ps.ColorBlendMode.NormalBlendColor, 100, False)
    else:
        ps.echo("Can't perform operation on background layer.")
```

**Comment by kratosvn** [comment]
Thank @loonghao for your support,

I found my way to change color:
`
 desc = Dispatch("Photoshop.ActionDescriptor")
    ref = Dispatch("Photoshop.ActionReference")
    ref.PutEnumerated(app.StringIDToTypeID("contentLayer"), app.CharIDToTypeID("Ordn"), app.CharIDToTypeID("Trgt"))
    desc.PutReference(app.CharIDToTypeID("null"), ref)
    fillDesc = Dispatch("Photoshop.ActionDescriptor")
    colorDesc = Dispatch("Photoshop.ActionDescriptor")
    colorDesc.PutDouble(app.CharIDToTypeID("Rd  "), colorObj.RGB.Red)
    colorDesc.PutDouble(app.CharIDToTypeID("Grn "), colorObj.RGB.Green)
    colorDesc.PutDouble(app.CharIDToTypeID("Bl  "), colorObj.RGB.Blue)
    fillDesc.PutObject(app.CharIDToTypeID("Clr "), app.CharIDToTypeID("RGBC"), colorDesc)
    desc.PutObject(app.CharIDToTypeID("T   "), app.StringIDToTypeID("solidColorLayer"), fillDesc)
    app.ExecuteAction(app.CharIDToTypeID("setd"), desc, 3)  # DialogModes.NO = 3 (No display dialog confirm)
`
