### ISSUE TITLE
Is it possible to detect a brush stroke?

### ISSUE THREAD

**Issue by marcouderzo** [loonghao/photoshop-python-api#43]
Hi, is it possible to detect when the user draws anything on the canvas?

**Comment by loonghao** [comment]
Sorry, I also don't know how to get this information.

Maybe you can try use [ScriptingListener](https://download.adobe.com/pub/adobe/photoshop/win/13.x/Win_Scripting_Plug-In.zip).

related url: 
- https://helpx.adobe.com/photoshop/kb/downloadable-plugins-and-content.html
- https://www.tranberry.com/photoshop/photoshop_scripting/tips/listener.html

**Comment by marcouderzo** [comment]
Thank you!
