### ISSUE TITLE
TextLayer.kind and TextLayer.justification properties don't exist

### ISSUE THREAD

**Issue by krevlinmen** [loonghao/photoshop-python-api#45]
I wrote this code:

def writeLayer(text):
    txtLayer = doc.artLayers.add()
    txtLayer.kind = ps.LayerKind.TextLayer
    txtLayer.textItem.contents = text
    txtLayer.textItem.kind = ps.TextType.ParagraphText
    txtLayer.textItem.justification = ps.Justification.Center
    
The problem is, the last 2 properties don't appear on Visual Code auto-complete, neither change anything in the new photoshop layer after executing the code.
Also, the constants do appear on Visual Code, only the properties themselves that don't.

I used the Photoshop JS scripting guide to figure out both of these properties:
https://wwwimages.adobe.com/www.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-cc-javascript-ref-2015.pdf#G4.368374

**Comment by loonghao** [comment]
@krevlinmen Thank you for your report. 
I will update and fix this issue on the weekend.

**Comment by loonghao** [comment]
@krevlinmen  I release new version is fix this issue, please let me know if that version work for you.

**Comment by loonghao** [comment]
@all-contributors please add krevlinmen for Bug reports.

**Comment by loonghao** [comment]
Closing the issue.
