### ISSUE TITLE
Is that possible to use photoshop-python-api in linux system?

### ISSUE THREAD

**Issue by Jiessie-jq** [loonghao/photoshop-python-api#46]
no winreg model

**Comment by joeygrable94** [comment]
I also have this question! Thanks for the contribution

**Comment by loonghao** [comment]
Unfortunately, Photoshop itself does not have a linux version.
This API is connected to Photoshop through  [COM](https://docs.microsoft.com/en-us/windows/win32/com/the-component-object-model) , so this API cannot be used in linux.

**Comment by sshallow** [comment]
你好，所以我想创建一个自动处理图片的python程序，运行到Linux服务器上，这是没法实现的吗？

**Comment by loonghao** [comment]
@sshallow 方便详细的说下你想要实现的程序功能？我知道有几种其他方法也行能满足你的需求

**Comment by sshallow** [comment]
我想实现自动爬取图片，并对图片进行一些处理（去水印，裁剪大小），裁剪我用的[PIL](https://github.com/python-pillow/Pillow)库，去水印我能想到的是使用photoshop 的仿制图章工具，所以才来找 ps 的 api，
