### ISSUE TITLE
support for python 3.4

### ISSUE THREAD

**Issue by WimWWimW** [loonghao/photoshop-python-api#47]
Only the use of f-strings prohibits the use of this library on python versions lower than 3.6.

A S&R over all files easily remedies this. Likely there are more elegant solutions, for f-strings are by no means essential.

used regex-patterns:

find: f'(.+)'
repl: '\1'.format\(**locals\(\)\)

find: f\"(.+)\"
repl: "\1".format\(**locals\(\)\)

**Comment by loonghao** [comment]
@WimWWimW I agreed with you I will find time update this. Thanks.

**Comment by loonghao** [comment]
@WimWWimW 
I tried to update to support python-3.4 but found that there will still be some compatibility issues. So I'm sorry that I don't want to spend too much time to be compatible with an old version. By the way, what kind of situation do you have to use this API in the 3.4 python environment?
