### ISSUE TITLE
Run outside python IDE of photoshop

### ISSUE THREAD

**Issue by Cold-A-Muse** [loonghao/photoshop-python-api#49]
I am looking into ways to automate photoshop scripting and stumbled on this library.
The example gif shows this library running from within photoshop. Is it possible to run the API from outside the IDE in the following way:
1. Open photoshop programatically
2. Adjusts text layers using photoshop-python-api
3. Save to new psd file

Also, would this work on mac as well or only Windows? 

Many thanks for answering!

**Comment by loonghao** [comment]
@Cold-A-Muse Unfortunately, currently, this API only supports the Windows version.
Since it is connected to Photoshop via COM, it can run in any environment with python-3, of course, you must install Photoshop locally.
