### ISSUE TITLE
How to get all the layers of a psd file and save the images in the layers to save them locally?

### ISSUE THREAD

**Issue by zhenzi0322** [loonghao/photoshop-python-api#60]
Does it also support getting the font and color of the text layer, etc.

**Comment by loonghao** [comment]
hi @zhenzi0322  you can test via in below codes
![image](https://user-images.githubusercontent.com/13111745/119215763-4cef1e00-bb02-11eb-8bbe-ff8c0772fbc4.png)

> How to get all the layers of a psd file and save the images in the layers to save them locally?

You can look at this
https://photoshop-python-api.readthedocs.io/en/0.15.1/examples.html#export-layers-as-png
