### ISSUE TITLE
Documents Class not subscriptable

### ISSUE THREAD

**Issue by SThomasN** [loonghao/photoshop-python-api#61]
**Describe the bug**
The "documents" class is supposed to be subscriptable but the class seems to be missing the "__getitem__()" method required to do so.

**To Reproduce**
import photoshop.api as ps
app = ps.Application()
app.documents[0]

**Expected behavior**
The following error should be returned:

"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Documents' object is not subscriptable"

**Screenshots**
![image](https://user-images.githubusercontent.com/63218023/119051104-bc450080-b990-11eb-96b8-04a2c906039f.png)

**Desktop (please complete the following information):**
 - OS: Windows10 Pro
 - Photoshop Version: Adobe Photoshop Version: 21.2.2 20200807.r.289 2020/08/07: 287d0d87ec  x64
 - Python Version: Python 3.8.3

**Additional context**
Please see Photoshop Scripting documentation on "Documents" class.
https://theiviaxx.github.io/photoshop-docs/Photoshop/Documents.html

**Comment by loonghao** [comment]
Hi, @SThomasN  Thank you for your report. I checked the code again and found that I did not implement this function. I will create a new MR to update it.

**Comment by loonghao** [comment]
Hi, @SThomasN I have been released a new version to implement this function. Thank you!

@all-contributors please add @SThomasN for Bug reports.
