### ISSUE TITLE
I can't open the psd file, I get an error when I run it

### ISSUE THREAD

**Issue by zhenzi0322** [loonghao/photoshop-python-api#62]
```python
import os

from photoshop import Session


def hide_all_layers(layers):
    for layer in layers:
        layer.visible = False


def main():
    psd_file = 'demo1.psd'
    with Session(psd_file, action="open") as ps:
        doc = ps.active_document
        options = ps.PNGSaveOptions()
        layers = doc.artLayers
        for layer in layers:
            hide_all_layers(layers)
            layer.visible = True
            layer_path = os.path.join(doc.path, layer.name)
            print(layer_path)
            if not os.path.exists(layer_path):
                os.makedirs(layer_path)
            image_path = os.path.join(layer_path, f"{layer.name}.png")
            doc.saveAs(image_path, options, True)
        ps.alert("Task done!")
        ps.echo(doc.activeLayer)


if __name__ == "__main__":
    main()
```
tips:
> `_ctypes.COMError: (-2147220262, None, (None, None, None, 0, None))`。

I get an error running directly from the library when I use the documentation：
[https://photoshop-python-api.readthedocs.io/en/0.15.1/examples.html#export-layers-as-png](https://photoshop-python-api.readthedocs.io/en/0.15.1/examples.html#export-layers-as-png)

**Comment by loonghao** [comment]
@zhenzi0322 You can first test and replace the path of your PSD with an absolute path and please tell me your python version and photoshop version.

**Comment by zhenzi0322** [comment]
> @zhenzi0322 You can first test and replace the path of your PSD with an absolute path and please tell me your python version and photoshop version.

python version is 3.7.5，photoshop-python-api==0.15.1

**Comment by zhenzi0322** [comment]
> @zhenzi0322 You can first test and replace the path of your PSD with an absolute path and please tell me your python version and photoshop version.

I want to extract all the information of the layers in the psd file, or download the images locally if they are images.

**Comment by loonghao** [comment]
@zhenzi0322 

this module depends you local install photoshop

> I want to extract all the information of the layers in the psd file, or download the images locally if they are images.

If you want to use this module in a web application, I suggest you take a look, it may be more suitable and easier to deploy

**Comment by zhenzi0322** [comment]
> @zhenzi0322
> 
> this module depends on you local install photoshop
> 
> > I want to extract all the information of the layers in the psd file, or download the images locally if they are images.
> 
> If you want to use this module in a web application, I suggest you take a look, it may be more suitable and easier to deploy
> 
> https://psd-tools.readthedocs.io/en/latest/

I have used this one and it has one disadvantage: it does not get the colour of the text.
The author did not reply to me.
