### ISSUE TITLE
The link to the documentation in the README will not open for me. Also thank you guys so much for making this I am really excited to use it!

### ISSUE THREAD

**Issue by adgotts** [loonghao/photoshop-python-api#67]
Getting a "sorry this page does not exist yet" error

**Comment by loonghao** [comment]
Hi @adgotts 

You can temporarily refer to this version of the document,

https://photoshop-python-api.readthedocs.io/en/0.15.1/

I will find time to fix this issue

Thank you

**Comment by loonghao** [comment]
Hi @adgotts 
I have already  update the document for API

https://loonghao.github.io/photoshop-python-api/
![image](https://user-images.githubusercontent.com/13111745/129471596-4ddb3169-153a-4750-aff7-97db3654e543.png)

![image](https://user-images.githubusercontent.com/13111745/129471567-0cc0f019-bc9d-4459-8dea-a91cfb817f40.png)

Cheers,
Hal
