### ISSUE TITLE
Installation difficulties

### ISSUE THREAD

**Issue by CaptainCsaba** [loonghao/photoshop-python-api#68]
Hello. I am trying to install the package via various means described in the documentation. None of them have worked for some reason. I would love to use your package, that is why I am writing this. If this is a noob mistake on my part, I apologise in advance.

If I install the package via the 'pip install python_photoshop_api' command it does not actually gets installed. If I navigate to my Python39/Lib/site-packages/photoshop_python_api-0.16.0.dist-info directory there are these files present, but no .py files that could actually be imported:

INSTALLER
LICENSE
METADATA
RECORD
REQUESTED
WHEEL

Thus I'm getting the "ModuleNotFoundError:  No module named 'photoshop'".

If I try to install it via the tarball, the link is taking me to a Github error 404 page.

I also tried GIT cloning. I've placed the downloaded folder into my Python39/Lib/site-packages directory. I've tried to import session via the 'from photoshop_python_api.src.photoshop.session import Session' command but it still gives me the "ModuleNotFoundError: No module named 'photoshop'".

Additional info:
- I have downloaded many other packages over the past months via pip install, all are importable.
- There are no environments.
- Photoshop 2021 is installed. Adobe Photoshop Version: 22.1.0 20201125.r.94
- I am using Python 3.9.1.
- I am using Windows 10. 
- There are also no other versions of Python installed, so I have just 1 interpreter.
- For editing I am using VS Code.

How come I can't install the package?

**Comment by loonghao** [comment]
Hi @CaptainCsaba I have been deployed a new version to fix that

@all-contributors please add @CaptainCsaba for Bug reports.
