### ISSUE TITLE
> > Hi, is there a way i can change the image on a specific layer? Thanks

### ISSUE THREAD

**Issue by loonghao** [loonghao/photoshop-python-api#72]
> > Hi, is there a way i can change the image on a specific layer? Thanks
> 
> @ConnorCampagnaDeveloper
> Do you give me more contextual information?
> Do you mean to replace the image by replacing the layer?

for instance if I have a layer called "Player" and i have another layer called "Game", they both contain images, but i want to change the image of both these to 2 another 2 images.  so instead of me changing the image on the active layer i would like to change it on another layer which i do not have selected. 

Thanks :)

_Originally posted by @ConnorCampagnaDeveloper in https://github.com/loonghao/photoshop-python-api/issues/38#issuecomment-888250545_

**Comment by loonghao** [comment]
@ConnorCampagnaDeveloper you can try below code

```python
from photoshop import Session

images = {
    "Player": r"xxxxxx.png",
    "Game": r"xxxxxx.png"
}

with Session() as ps:
    for layer in ps.active_document.layers:
        if layer.name in images.keys():
            ps.active_document.activeLayer = layer
            replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
            desc = ps.ActionDescriptor
            idnull = ps.app.charIDToTypeID("null")
            new_image = images[layer.name]
            desc.putPath(idnull, new_image)
            print(f"Replace to {new_image}")
            ps.app.executeAction(replace_contents, desc)

```
Let me know if that works for you,

Cheers,
Hal

**Comment by ConnorCampagnaDeveloper** [comment]
Thank You So Much :) Works Now Have A Good Day 👍 🥇

**Comment by Mossad-55** [comment]
It works but it seems whenever i try to put the desiered image it gets way bigger so i do in photoshop to press reset transforms is there a way to fix that, and thanks in advance.
