### ISSUE TITLE
 is there any  methods  to rename the existing  picture   layers  

### ISSUE THREAD

**Issue by brightendavid** [loonghao/photoshop-python-api#73]
when I add  picture as a layer,and the name  of the layer  will be the name of the picture

I could not find any  methods  to rename the existing  layers.

and I use      `desc.putPath(ps.app.charIDToTypeID("null"),images["src"])`     to add layer

**Comment by loonghao** [comment]
Hi @brightendavid Get the currently active document and layer activity to set a new name.

Below is a real code
```python
from photoshop import Session

with Session() as ps:
    layer = ps.active_document.activeLayer
    print(f"old name: {layer.name}")
    layer.name = "new name"
    print(f"new name: {layer.name}")
```
Let me know if this works for you

Cheers,
Hal

**Comment by brightendavid** [comment]
`from photoshop import Session
"""Import a image as a artLayer."""

# Import local modules

with Session(action="new_document") as ps:
    desc = ps.ActionDescriptor
    desc.putPath(ps.app.charIDToTypeID("null"), r"C:\Users\new_data\plan2\pic_test_file\src.png")
    event_id = ps.app.charIDToTypeID("Plc ")  # `Plc` need one space in here.
    ps.app.executeAction(ps.app.charIDToTypeID("Plc "), desc)`

I am sorry not express well . look at the example,this is the example file  you applyed.the  added layer may always have the name src.and  I just can't  rename the layer .The added  layer may not have the **attribute**  "Name".

**Comment by loonghao** [comment]
@brightendavid 
I have quickly tested its works, could you please give more context information(python version, photoshop version, and error screenshot)?

![import_image](https://user-images.githubusercontent.com/13111745/127949077-53e4d64c-3ad7-4417-9ce9-0b75e0135e48.gif)

```python
from photoshop import Session

with Session(action="new_document") as ps:
    desc = ps.ActionDescriptor
    desc.putPath(ps.app.charIDToTypeID("null"),
                 r"C:\Users\hallong\Pictures\332-3328628_refresh-icon-vector-clipart.png")
    event_id = ps.app.charIDToTypeID("Plc ")  # `Plc` need one space in here.
    ps.app.executeAction(ps.app.charIDToTypeID("Plc "), desc)
    layer = ps.active_document.activeLayer
    layer.name = "new_name"
```

**Comment by brightendavid** [comment]
thank you very much ,it is all right now. I may  make a mistake. 
![image](https://user-images.githubusercontent.com/66240251/127949782-696aa26e-c0e6-4354-a2a0-9b1893872ff9.png)

**Comment by loonghao** [comment]
You're welcome!

Closing the issue.
