### ISSUE TITLE
how to imprt PDF files correctly

### ISSUE THREAD

**Issue by jaye-li** [loonghao/photoshop-python-api#82]
deer author：
  I cannt undersatand the meaning of this row : 
![image](https://user-images.githubusercontent.com/79128143/133271117-987f5d8e-f0ae-48c1-9475-9033ec15b916.png)
  The variable 'event_id' is not referenced by any thing,but when I copied this example in my pycharm,it showed like that have be referenced.
  And in my progress,I commented out this line of code,the program can also be runned successfully,so what's the meaning of it?
![image](https://user-images.githubusercontent.com/79128143/133273303-109ff4db-5302-4b06-a455-c334feeae44d.png)
  Though I used the methord in example 'Import Image As Layer' to import my PDF files as layers successfully, I want to make sure that if have the proprietary event id for importing PDF.
  I also want to know why the 《event_id.py》donnt have the value 'null',but the putPath-methord's parameter 'ps.app.charIDToTypeID("null")' can be readed correctly?
![image](https://user-images.githubusercontent.com/79128143/133277380-fa9de15f-53d3-4ef8-89c9-c3299bfbeef1.png)
![image](https://user-images.githubusercontent.com/79128143/133277539-506e2884-bac9-4584-b0aa-7916a39ca4cd.png)

Thanks for your answer!

@loonghao

**Comment by loonghao** [comment]
They are two different things, one is a constant and the other is a string
