### ISSUE TITLE
Get text layer font size incorect

### ISSUE THREAD

**Issue by Upfunny** [loonghao/photoshop-python-api#84]
**Describe the bug**
[psdfile.zip](https://github.com/loonghao/photoshop-python-api/files/7167289/psdfile.zip)

There is two Text layer in the psd file, when I get the font size, 
one of the font size value is right, the other one is wrong, but in Photoshop, they are both 48

layername: wrong font_size: 22.33272933959961
layername: right font_size: 48.0

by the way how to get the text width? I can't get the layer.textItem.width value

**To Reproduce**

import photoshop.api as ps
app = ps.Application()
doc = app.load(r'C:\1.psd')
for layer in doc.layers:
    print('layername:', layer.name, 'font_size:', layer.textItem.size)
doc.close()

**Desktop (please complete the following information):**
 - OS: Windows10,
 - Photoshop Version: Photoshop-2021
 - Python Version: python-3.9.5

**Comment by loonghao** [comment]
@Upfunny 
I have made some tests, when I mean to change the text layer you can see the gif. the layer has some moment the size is display wrong. when I delete the wrong name and create a new one we can get the corect size.
you can try deleting the wrong text layer and create a new layer again
![ps_api_test](https://user-images.githubusercontent.com/13111745/133928472-5808857b-fea1-461b-b919-96f676bf1434.gif)
 
![ps_api_test_2](https://user-images.githubusercontent.com/13111745/133928696-ff3f0ed3-18a2-4180-845a-88bf9f3f3934.gif)

**Comment by Upfunny** [comment]
Thanks for your reply
But I have tooooo many psd... So I don't want to test and modify one by one😭

**Comment by loonghao** [comment]
@Upfunny 
I think you can batch process through this API
According to your uniform size, loop all layers, check the size, delete the bad layer, and then recreate and assign back to the original data
