### ISSUE TITLE
How do I replace an image on a normal layer in a PSD file and keep the replacement image in the same place  ?

### ISSUE THREAD

**Issue by tzl1** [loonghao/photoshop-python-api#87]
My environment:
    Windows 7
    python3.6
    ps2018
    photoshop-python-api    0.16.3

I tried something like manually converting a normal layer into a smart object and then calling API to replace the image, but the image would be offset.

**Comment by loonghao** [comment]
@tzl1 Can you give me more contextual information?
How is your test code written? Is the size of your test file the same?
