### ISSUE TITLE
how can change different style in one textlayer

### ISSUE THREAD

**Issue by Upfunny** [loonghao/photoshop-python-api#91]
There is a textlayer，The text is 'good job，bro~!'
I want to change 'good job' color to red , 'bro~!' to green,
Maybe change the font or orther styles 
In Photoshop I can edit the style easily, but how do I edit it in photoshop-python-api?

 - OS: Windows10
 - Photoshop Version: Photoshop-202
 - Python Version: python-3.9.7

**Comment by loonghao** [comment]
@Upfunny Sorry, I am no idea how to use photoshop JS API to do this.
If we can use Photoshop JS API to implement this function, then we can easily convert to PYPS API to execute

**Comment by Upfunny** [comment]
> @Upfunny Sorry, I am no idea how to use photoshop JS API to do this. If we can use Photoshop JS API to implement this function, then we can easily convert to PYPS API to execute

thank you for your reply~
