### ISSUE TITLE
Can we use this library on cloud? 

### ISSUE THREAD

**Issue by rupeshchandgude** [loonghao/photoshop-python-api#95]
Hi I have to write a code, which takes multiple images as an input and give psd file as an output with those image as layers. I need t run this code on cloud, Can I use this package for this task? As I am doubtful this will run on cloud.

**Comment by loonghao** [comment]
Hi @rupeshchandgude , this API is dependent on Adobe Photoshop application.
So it can't be run in the cloud.
Maybe you can check out https://www.adobe.io/photoshop/api/
